### ISSUE TITLE
[Forge 1.20.1] Can't converted dyed covered cables into smart cables of the same colour without using extra dye

### ISSUE THREAD

**Issue by vizthex123** [Lafen99/AE2-QoL-Recipes#1]
Specifically, this recipe:
![image](https://github.com/Christofmeg/AE2-QoL-Recipes/assets/31721920/81c4cd92-8060-4462-b1fc-2914ccf031a4)

There should be a version that uses the dyed covered cable colour + redstone & glowstone dust to make a smart cable of the same colour.

_Also, the mod should remove the default "chest shape + dye" recipes for cables and replace it with the tagged version._

**Comment by Christofmeg** [comment]
> Also, the mod should remove the default "chest shape + dye" recipes for cables and replace it with the tagged version.

I could implement this feature by replacing the normal ae2 cable recipes. But these "updated recipes" would only work on worlds that are created after this update. And would be incompatible with pre-existing worlds.

**Comment by Christofmeg** [comment]
Fixed in version 1.2.0.

**Comment by vizthex123** [comment]
damn nice!

**Comment by vizthex123** [comment]
> > Also, the mod should remove the default "chest shape + dye" recipes for cables and replace it with the tagged version.
> 
> I could implement this feature by replacing the normal ae2 cable recipes. But these "updated recipes" would only work on worlds that are created after this update. And would be incompatible with pre-existing worlds.

That'd be fine (as long as it doesn't brick you world or something).

Thanks for fixing it!
